name: Deploy MkDocs (gh-pages)

on:
  push:
    branches: [ master ]

permissions:
  contents: write

concurrency:
  group: mkdocs-gh-deploy
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # or keep '3.x'

      # 1) System deps for CairoSVG (needed for social cards)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2

      # 2) Python deps incl. imaging extras
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -U mkdocs mkdocs-material "mkdocs-material[imaging]"

      # (Optional but avoids git identity errors on gh-deploy)
      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3) Build & deploy to gh-pages
      - name: Build & deploy
        run: mkdocs gh-deploy --force
